import " /styles/globals.css";

import {ClerkProvider} from '@clerk/nextjs'
import { Noto_Kufi_Arabic } from "next/font/google";
import { type Metadata } from "next";

import { TRPCReactProvider } from " /trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontArabic = Noto_Kufi_Arabic({ subsets: ['arabic'] }) 

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
    <html lang="en" className={`${fontArabic.className} bg-[#FDF4EF]`}>
      <body>
        <TRPCReactProvider>
          {children}
        </TRPCReactProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
